@echo off
IF NOT EXIST RecoveredInformation (
    mkdir RecoveredInformation
)
goto main
:main
cls
color 70
title WiFi Password Recovery v0x_1
echo Welcome to Tymo's Public Password Recovery Program!, Here are all the WiFi networks you can recover:
netsh wlan show profile
echo.
set /p id=Network Name :: 
cls
echo :: Succesfully Recovered Information for %id%.
echo.
netsh wlan show profile %id% key=clear
echo.
echo.
echo Do you want to save this information to %id%.txt? [Y/N]
echo.
set /p two=:: 
if "%two%"=="Y" goto SaveToFile
if "%two%"=="y" goto SaveToFile
if "%two%"=="N" goto Done
if "%two%"=="n" goto Done
:SaveToFile
if EXIST %id%.txt (
    del %id%.txt
)
echo :: This file is generated by Tymo's Public Password Recovery! :: >> %id%.txt
echo :: Last overwrite on %DATE% at %TIME% :: >> %id%.txt
echo. >> %id%.txt
netsh wlan show profile %id% key=clear >> %id%.txt
echo.
echo %id%.txt was Succesfully created/overwritten with all the information, Press any key to continue!
pause > nul
goto main
:Done
cls
echo :: You did not save the Information to %id%.txt ::
echo.
netsh wlan show profile %id% key=clear
echo.
echo Press any key to go back to the main screen.
pause > nul
goto main
